Repository autolab/Autolab, pull requests merged in 2022-08, with the labels that each got.

#1576 Update macOS docs to fix mysql link, install ordering of steps
  docs/installation/osx.md
Labels: Type: Maintenance, Priority: Low

#1578 Disable version switching feature when displaying autograder output
  app/controllers/submissions_controller.rb
Labels: Priority: Medium, Type: Bug

#1579 Fix remarks for annotations on autograder output
  app/views/assessments/viewFeedback.html.erb
Labels: Priority: Low, Type: Bug

#1580 Add mononym support
  app/assets/javascripts/watchlist.js
  app/controllers/assessment/grading.rb
  app/controllers/courses_controller.rb
  app/controllers/scoreboards_controller.rb
  app/models/user.rb
  app/views/assessments/viewGradesheet.html.erb
  app/views/course_user_data/index.html.erb
  app/views/course_user_data/show.html.erb
  app/views/course_user_data/user.html.erb
  app/views/submissions/index.html.erb
  app/views/users/show.html.erb
Labels: Type: Enhancement, Priority: Low
