Repository autolab/Autolab, pull requests merged in 2022-09, with the labels that each got.

#1583 Update readme
  README.md
Labels: Type: Maintenance, Priority: Low

#1584 Fix creation of missing submissions
  app/views/components/_autocomplete.html.erb
  app/views/submissions/new.html.erb
Labels: Priority: Medium, Type: Bug

#1585 Standardize roster upload tables
  app/views/courses/_uploadError.html.erb
  app/views/courses/_uploadTable.html.erb
Labels: Priority: Low, Type: Bug

#1586 Pre-validate user creation in course_user_data/new
  app/controllers/course_user_data_controller.rb
Labels: Priority: Low, Type: Bug
