Repository autolab/Autolab, pull requests merged in 2022-07, with the labels that each got.

#1554 Update ctags installation instructions
  docs/installation/one-click.md
  docs/installation/osx.md
  docs/installation/tango.md
  docs/installation/ubuntu.md
  docs/tango-cli.md
Labels: Priority: Low, Type: Bug

#1556 Update README.md
  README.md
Labels: Type: Maintenance, Priority: Low

#1515 Consistent annotation alternative implementation
  app/controllers/annotations_controller.rb
  app/controllers/submissions_controller.rb
  app/helpers/assessment_handin_core.rb
  app/models/annotation.rb
  app/models/submission.rb
  db/migrate/20220424202745_add_group_key_to_submissions.rb
  db/schema.rb
Labels: Priority: Medium, Type: Bug

#1557 Fix roster format
  app/controllers/courses_controller.rb
Labels: Priority: Medium, Type: Bug

#1560 Do not run :log_entry on :destroy
  app/models/score.rb
Labels: Priority: Low, Type: Bug

#1559 Fix statistics page for problemless assessment
  app/controllers/assessment/grading.rb
Labels: Priority: Low, Type: Bug

#1564 Include CSRF token for Git submissions
  app/assets/javascripts/git_submission.js
Labels: Priority: High, Type: Bug

#1563 Fix CA redirection when downloadAll called with no submissions
  app/controllers/submissions_controller.rb
Labels: Priority: Low, Type: Bug

#1561 Make assessment imports from file system have more clear error messages
  app/controllers/assessments_controller.rb
  app/views/assessments/install_assessment.html.erb
Labels: Type: Enhancement, Priority: Low

#1552 Rails 6.0.5 Migration
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/attachments_controller.rb
  app/controllers/course_user_data_controller.rb
  app/controllers/courses_controller.rb
  app/controllers/problems_controller.rb
  app/controllers/submissions_controller.rb
  app/models/risk_condition.rb
  app/views/doorkeeper/authorizations/new.html.erb
  app/views/schedulers/index.html.erb
  app/views/scoreboards/_form.html.erb
  app/views/users/edit.html.erb
  bin/rails
  bin/rake
  bin/setup
  config/application.rb
  config/cable.yml
  config/environments/development.rb
  config/environments/test.rb
  config/initializers/assets.rb
  config/initializers/content_security_policy.rb
  config/initializers/new_framework_defaults_6_0.rb
  config/locales/en.yml
  config/routes.rb
  config/spring.rb
  config/storage.yml
  db/migrate/20220710081832_add_foreign_key_constraint_to_active_storage_attachments_for_blob_id.active_storage.rb
Labels: Priority: High, Type: Maintenance

#1565 Indent folders in speedgrader file outline
  app/assets/stylesheets/annotations.css
Labels: Priority: Low, Type: Bug

#1562 Disable user data fields during CUD edit
  app/views/course_user_data/_fields.html.erb
  app/views/course_user_data/edit.html.erb
  app/views/course_user_data/new.html.erb
Labels: Priority: Low, Type: Bug

#1566 Alphabetically sort extracted archive files
  lib/archive.rb
Labels: Type: Enhancement, Priority: Low

#1568 Revert "Alphabetically sort extracted archive files"
  lib/archive.rb
Labels: Priority: Critical, Type: Bug

#1569 [hotfix] Update the name for group settings function
  app/controllers/api/v1/assessments_controller.rb
Labels: Priority: High, Type: Bug

#1571 Fix Autograder Output on View Submission Page
  app/controllers/submissions_controller.rb
Labels: Priority: High, Type: Bug

#1503 Submission Version Switching
  app/assets/javascripts/annotations.js
  app/controllers/submissions_controller.rb
  app/views/submissions/_version_links.html.erb
  app/views/submissions/view.html.erb
  app/views/submissions/view.js.erb
Labels: Type: Enhancement, Priority: Low

#1572 Metrics hotfix
  app/controllers/metrics_controller.rb
  app/models/watchlist_instance.rb
Labels: Priority: High, Type: Bug

#1573 [hotfix] Fix PDF viewer on autograded assignments
  app/controllers/submissions_controller.rb
  app/views/submissions/_annotations_js.html.erb
  app/views/submissions/_code_symbol_tree.html.erb
Labels: Priority: Medium, Type: Bug

#1574 Trim prerenders
  app/views/submissions/_version_links.html.erb
  app/views/submissions/view.html.erb
Labels: Priority: Low, Type: Bug
