Repository autolab/Autolab, pull requests merged in 2023-06, with the labels that each got.

#1915 Remove unused errors column from submission history table
  app/controllers/assessments_controller.rb
  app/views/assessments/_submission_history_row.html.erb
  app/views/assessments/_submission_history_table.html.erb
Labels: small

#1918 Lint views/jobs
  app/views/jobs/getjob.html.erb
  app/views/jobs/index.html.erb
  app/views/jobs/tango_status.html.erb
Labels: small

#1920 Eager load course_user_datum for the index submission view
  app/controllers/submissions_controller.rb
Labels: small

#1911 Add explicit import button for import asmt from tar
  app/controllers/assessments_controller.rb
  app/controllers/courses_controller.rb
  app/models/course.rb
  app/views/assessments/install_assessment.html.erb
  spec/rails_helper.rb
Labels: medium

#1912 Correctly cache speedgrader symbol tree
  app/assets/javascripts/annotations.js
  app/views/submissions/view.js.erb
Labels: small

#1916 Improve Scheduler UI, visual run isolation, add until and disable options
  app/controllers/application_controller.rb
  app/controllers/schedulers_controller.rb
  app/models/scheduler.rb
  app/views/extensions/index.html.erb
  app/views/schedulers/create.html.erb
  app/views/schedulers/destroy.html.erb
  app/views/schedulers/edit.html.erb
  app/views/schedulers/index.html.erb
  app/views/schedulers/new.html.erb
  app/views/schedulers/run.html.erb
  app/views/schedulers/show.html.erb
  db/migrate/20230603073522_add_until_to_scheduler.rb
  db/migrate/20230603073633_add_disabled_to_scheduler.rb
  db/schema.rb
  docs/features/annotations.md
  docs/features/embedded-forms.md
  docs/features/formatted-feedback.md
  docs/features/schedulers.md
  docs/features/scoreboards.md
  docs/images/scheduler_visual_run.png
  docs/installation/one-click.md
  mkdocs.yml
Labels: large

#1922 Tango error flash: remove dead code and fix newline
  app/controllers/assessment/autograde.rb
Labels: small

#1913 Improve viewFeedback output parsing, error robustness
  app/controllers/assessments_controller.rb
  app/views/assessments/_results_panel.html.erb
  app/views/assessments/_semantic.html.erb
Labels: small

#1925 Sort scoreboard beyond third column, improve CUD validations
  app/assets/javascripts/course_user_data_edit.js
  app/controllers/course_user_data_controller.rb
  app/controllers/scoreboards_controller.rb
  app/models/course_user_datum.rb
  app/models/scoreboard.rb
  app/views/course_user_data/_fields.html.erb
  app/views/course_user_data/edit.html.erb
  app/views/course_user_data/new.html.erb
  app/views/scoreboards/show.html.erb
  docs/features/scoreboards.md
Labels: medium

#1929 Lock passenger-ruby27 to v2.5.0
  Dockerfile
Labels: small

#1921 Use custom error pages
  app/controllers/admins_controller.rb
  app/controllers/annotations_controller.rb
  app/controllers/announcements_controller.rb
  app/controllers/application_controller.rb
  app/controllers/assessment_user_data_controller.rb
  app/controllers/assessments_controller.rb
  app/controllers/attachments_controller.rb
  app/controllers/course_user_data_controller.rb
  app/controllers/courses_controller.rb
  app/controllers/extensions_controller.rb
  app/controllers/gradebooks_controller.rb
  app/controllers/groups_controller.rb
  app/controllers/home_controller.rb
  app/controllers/jobs_controller.rb
  app/controllers/problems_controller.rb
  app/controllers/schedulers_controller.rb
  app/controllers/scoreboards_controller.rb
  app/controllers/scores_controller.rb
  app/controllers/submissions_controller.rb
  app/controllers/users_controller.rb
  app/views/home/error_500.html.erb
  config/environments/development.rb
  config/environments/production.rb.template
  config/environments/test.rb
  config/initializers/doorkeeper.rb
  config/routes.rb
  public/404.html
  public/422.html
  public/500.html
  spec/controllers/home_controller_spec.rb
Labels: medium

#1930 Add student emails to downloadAll archives
  app/controllers/submissions_controller.rb
  lib/archive.rb
Labels: small
