Repository autolab/Autolab, pull requests merged in 2023-01, with the labels that each got.

#1678 Fixed LTI sync issue with admins
  app/controllers/lti_nrps_controller.rb
Labels: 1 min review

#1679 Send JSON error instead of entire 500 page error on autograde error
  app/controllers/assessments_controller.rb
Labels: 1 min review

#1684 Correctly display filename for annotations on first file of an archive
  app/controllers/application_controller.rb
Labels: 1 min review

#1682 Improve attachments interface and error handling
  app/controllers/attachments_controller.rb
  app/views/assessments/index.html.erb
  app/views/assessments/show.html.erb
  app/views/attachments/_assessment_attachment.html.erb
  app/views/attachments/_attachment.html.erb
  app/views/attachments/_course_attachment.html.erb
  app/views/attachments/index.html.erb
Labels: 10 min review

#1685 Change overflow-x on .submissions from scroll to auto
  app/assets/stylesheets/style.css.scss
Labels: 1 min review

#1674 Revamp getjobs UI
  app/assets/stylesheets/getjob.css.scss
  app/views/jobs/getjob.html.erb
Labels: 20 min review

#1673 Revamp Gradebook/Gradesheet to be more UI friendly
  app/assets/javascripts/SlickGrid/2.02/slick.grid.js
  app/assets/javascripts/gradebook.js
  app/assets/javascripts/gradesheet.js.erb
  app/assets/stylesheets/gradesheet.css.scss
  app/assets/stylesheets/instructor_gradebook.css
  app/views/assessments/_popover.html.erb
  app/views/assessments/viewGradesheet.html.erb
  app/views/gradebooks/view.html.erb
Labels: 20 min review

#1634 Add rake task to clean cache
  app/models/assessment_user_datum.rb
  app/models/course_user_datum.rb
  app/models/submission.rb
  docs/installation/troubleshoot.md
  lib/tasks/user.rake
Labels: Type: Maintenance, Priority: Low, 1 min review

#1687 Adds streaming output explanation into Lab author's guide
  docs/lab.md
Labels: 1 min review, safe-changes

#1683 Moved "Install Assessment" button to top box, removed "Instructor Actions" header, renamed Assignments header to Assessments
  app/views/assessments/index.html.erb
Labels: 5 min review

#1694 Remove "row metrics" class from install asmt button
  app/views/assessments/index.html.erb
Labels: 1 min review

#1693 Centralize Sass variables into single file
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/annotations.scss
  app/assets/stylesheets/assessments/quiz.css.scss
  app/assets/stylesheets/beta.scss
  app/assets/stylesheets/getjob.css.scss
  app/assets/stylesheets/git_submission.scss
  app/assets/stylesheets/gradesheet.css.scss
  app/assets/stylesheets/instructor_gradebook.scss
  app/assets/stylesheets/metrics.scss
  app/assets/stylesheets/metricsgraphics.scss
  app/assets/stylesheets/mobile.scss
  app/assets/stylesheets/scaffold.scss
  app/assets/stylesheets/style.css.scss
  app/assets/stylesheets/usersTable.css.scss
  config/initializers/assets.rb
Labels: 20 min review

#1689 Input pre-validation on sign-up page
  app/assets/javascripts/signup_form.js
  app/assets/stylesheets/style.css.scss
  app/models/user.rb
  app/views/devise/registrations/new.html.erb
Labels: 10 min review

#1739 Fix footer on course view page
  app/views/assessments/index.html.erb
Labels: 1 min review
