Repository autolab/Autolab, pull requests merged in 2023-04, with the labels that each got.

#1840 Version dropdown: jump to same file if it exists
  app/assets/javascripts/annotations.js
  app/assets/stylesheets/annotations.scss
  app/controllers/submissions_controller.rb
  app/models/submission.rb
  app/views/submissions/_version_dropdown.html.erb
  app/views/submissions/view.html.erb
  app/views/submissions/view.js.erb
Labels: 5 min review

#1846 Implement Backwards Compatibility to Per-user Handin Subdirectories
  app/models/submission.rb
Labels: 1 min review

#1831 [Breaking] Create per-user handin subdirectories
  app/helpers/assessment_autograde_core.rb
  app/models/submission.rb
Labels: 10 min review

#1832 Adds modifySubmissionScores hook
  app/helpers/assessment_autograde_core.rb
  app/models/assessment.rb
  docs/lab.md
Labels: 1 min review

#1864 Add Backwards Compatibility to ActiveStorage Attachments
  app/controllers/attachments_controller.rb
Labels: 1 min review

#1866 [Cherry Picked] Adds modifySubmissionScores hook
  app/helpers/assessment_autograde_core.rb
  app/models/assessment.rb
  docs/lab.md
Labels: 1 min review

#1858 Refactor testing sets
  spec/contexts_helper.rb
  spec/controllers/annotations_controller_spec.rb
  spec/models/annotation_spec.rb
  spec/sets/assessments.rb
  spec/sets/courses.rb
  spec/sets/problems.rb
  spec/sets/submissions.rb
  spec/support/controller_macros.rb
Labels: 10 min review

#1868 Center checkbox in manage submission table
  app/assets/stylesheets/style.css.scss
  app/views/submissions/index.html.erb
Labels: 1 min review

#1871 Use communityinviter for slack invites
  README.md
  docs/installation/docker-compose.md
  docs/installation/tango-troubleshoot.md
Labels: 1 min review, safe-changes

#1879 Fix placeholder for DEVISE_SECRET_KEY
  .env.template
Labels: 1 min review

#1881 Simplify initialize_secrets.sh, fix dockerfile
  Dockerfile
  bin/initialize_secrets.sh
Labels: 1 min review

#1872 Add size limit to attachments
  app/controllers/attachments_controller.rb
  app/models/attachment.rb
  app/views/attachments/_form.html.erb
Labels: 1 min review

#1870 Google OAuth Config UI
  .gitignore
  Gemfile
  Gemfile.lock
  app/assets/javascripts/autolab_config.js
  app/controllers/admins_controller.rb
  app/controllers/oauth_config_controller.rb
  app/models/user.rb
  app/views/admins/_oauth_integration.html.erb
  app/views/admins/autolab_config.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.erb
  config/initializers/devise.rb
  config/routes.rb
  public/images/google_logo.png
Labels: 10 min review

#1885 Delete unused destroy html erb file
  app/views/assessments/destroy.html.erb
Labels: 1 min review

#1889 Gitstream: Don't attempt to assign PR author as reviewer
  .cm/gitstream.cm
Labels: cm-changes

#1888 Fix hovering over top navbar to be colored white instead of blue for Metrics page
  app/assets/stylesheets/metrics.scss
Labels: 1 min review

#1883 Add user interface to upload config files, revamp file input fields
  app/assets/stylesheets/style.css.scss
  app/controllers/assessments_controller.rb
  app/controllers/courses_controller.rb
  app/form_builders/form_builder_with_date_time_input.rb
  app/models/assessment.rb
  app/views/assessments/_bulkGrade_initial.html.erb
  app/views/assessments/_edit_advanced.html.erb
  app/views/assessments/_edit_basic.html.erb
  app/views/assessments/_edit_handin.html.erb
  app/views/assessments/_upload_form.html.erb
  app/views/assessments/bulkGrade.html.erb
  app/views/assessments/new.html.erb
  app/views/assessments/reload.html.erb
  app/views/attachments/_form.html.erb
  app/views/autograders/_form.html.erb
  app/views/courses/_courseFields.html.erb
  app/views/courses/edit.html.erb
  app/views/courses/reload.html.erb
  app/views/submissions/new.html.erb
  lib/__defaultCourse.rb
Labels: 1 min review

#1891 Fix floating thead on manage users and missing submissions pages
  app/assets/stylesheets/datatable.adapter.css
  app/assets/stylesheets/style.css.scss
  app/assets/stylesheets/users.css.scss
  app/views/courses/_usersTable.html.erb
  app/views/courses/users.html.erb
  app/views/submissions/index.html.erb
  app/views/submissions/missing.html.erb
  config/initializers/assets.rb
Labels: 1 min review

#1890 Add sorting icons to new manage submissions
  app/assets/stylesheets/style.css.scss
  app/views/submissions/index.html.erb
Labels: 1 min review

#1887 Implement export course
  app/assets/stylesheets/export.scss
  app/controllers/courses_controller.rb
  app/models/attachment.rb
  app/models/course.rb
  app/models/risk_condition.rb
  app/models/watchlist_configuration.rb
  app/views/courses/_exportForm.html.erb
  config/routes.rb
  spec/contexts_helper.rb
  spec/controllers/courses_controller_spec.rb
  spec/factories/attachments.rb
  spec/factories/courses.rb
  spec/sets/courses.rb
Labels: 20 min review
