Repository autolab/Autolab, pull requests merged in 2023-09, with the labels that each got.

#1965 Lint views/groups
  app/views/groups/_form.html.erb
  app/views/groups/_list_item.html.erb
  app/views/groups/_new_form.html.erb
  app/views/groups/index.html.erb
  app/views/groups/new.html.erb
  app/views/groups/show.html.erb
Labels: small

#1976 Autolab v2.11.1
  config/application.rb
  spec/rails_helper.rb
Labels: small

#1964 lint views/course_user_data
  app/views/course_user_data/_fields.html.erb
  app/views/course_user_data/edit.html.erb
  app/views/course_user_data/index.html.erb
  app/views/course_user_data/new.html.erb
  app/views/course_user_data/show.html.erb
  app/views/course_user_data/sudo.html.erb
  app/views/course_user_data/user.html.erb
Labels: medium

#1960 Lint views/problems
  app/assets/stylesheets/problems.css.scss
  app/views/problems/_fields.html.erb
  app/views/problems/edit.html.erb
  app/views/problems/new.html.erb
Labels: small

#1974 Lint views/courses and fix up run_moss UI
  app/assets/stylesheets/style.css.scss
  app/views/components/_dropdown_icon.html.erb
  app/views/courses/_courseFields.html.erb
  app/views/courses/_updateRosterPreview.html.erb
  app/views/courses/_uploadError.html.erb
  app/views/courses/_uploadTable.html.erb
  app/views/courses/_usersTable.html.erb
  app/views/courses/download_roster.html.erb
  app/views/courses/edit.html.erb
  app/views/courses/email.html.erb
  app/views/courses/index.html.erb
  app/views/courses/makeDlist.html.erb
  app/views/courses/manage.html.erb
  app/views/courses/moss.html.erb
  app/views/courses/new.html.erb
  app/views/courses/reload.html.erb
  app/views/courses/report_bug.html.erb
  app/views/courses/run_moss.html.erb
  app/views/courses/upload_roster.html.erb
  app/views/courses/users.html.erb
Labels: large

#1958 Lint views/users
  app/assets/stylesheets/users.css.scss
  app/controllers/users_controller.rb
  app/views/users/_fields.html.erb
  app/views/users/_form.html.erb
  app/views/users/edit.html.erb
  app/views/users/index.html.erb
  app/views/users/lti_launch_initialize.html.erb
  app/views/users/new.html.erb
  app/views/users/show.html.erb
  spec/controllers/users_controller_spec.rb
Labels: medium

#1966 Lint views/gradebook
  app/views/gradebooks/statistics.html.erb
  app/views/gradebooks/student.html.erb
  app/views/gradebooks/view.html.erb
Labels: small

#1959 Lint views/scoreboards
  app/views/scoreboards/_form.html.erb
  app/views/scoreboards/show.html.erb
Labels: small

#1978 lint views/layouts
  app/views/layouts/_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/doorkeeper/admin.html.erb
Labels: medium

#1967 Lint views/admins, views/application, views/assessment_user_data, views/attachments
  app/views/application/maintenance.html.erb
  app/views/assessment_user_data/edit.html.erb
  app/views/attachments/_attachment.html.erb
  app/views/attachments/_form.html.erb
  app/views/attachments/edit.html.erb
  app/views/attachments/index.html.erb
  app/views/attachments/new.html.erb
Labels: medium

#1980 Lint views/doorkeeper and remove more unused files
  app/views/doorkeeper/applications/_delete_form.html.erb
  app/views/doorkeeper/applications/_form.html.erb
  app/views/doorkeeper/applications/show.html.erb
  app/views/doorkeeper/authorizations/new.html.erb
  app/views/doorkeeper/authorizations/show.html.erb
  app/views/doorkeeper/authorized_applications/index.html.erb
  lib/modules/views/adminScoreboard.html.erb
  lib/modules/views/autograderDev.html.erb
Labels: small

#1970 Lint views/assessments
  app/views/assessments/_autoCompleteAndrewID.html.erb
  app/views/assessments/_bulkGrade_initial.html.erb
  app/views/assessments/_downloadSubmission.html.erb
  app/views/assessments/_edit_advanced.html.erb
  app/views/assessments/_edit_basic.html.erb
  app/views/assessments/_edit_handin.html.erb
  app/views/assessments/_edit_penalties.html.erb
  app/views/assessments/_edit_problems.html.erb
  app/views/assessments/_handin_form.html.erb
  app/views/assessments/_partial_feedback_js.html.erb
  app/views/assessments/_popover.html.erb
  app/views/assessments/_remarks_panel.html.erb
  app/views/assessments/_results_panel.html.erb
  app/views/assessments/_semantic.html.erb
  app/views/assessments/_statistics.html.erb
  app/views/assessments/_submission_history_row.html.erb
  app/views/assessments/_submission_history_table.html.erb
  app/views/assessments/_submission_panel.html.erb
  app/views/assessments/_submission_summary_row.html.erb
  app/views/assessments/admin_svn.html.erb
  app/views/assessments/attachments.html.erb
  app/views/assessments/bulkGrade.html.erb
  app/views/assessments/bulkGrade_complete.html.erb
  app/views/assessments/edit.html.erb
  app/views/assessments/handout.html.erb
  app/views/assessments/history.html.erb
  app/views/assessments/index.html.erb
  app/views/assessments/install_assessment.html.erb
  app/views/assessments/new.html.erb
  app/views/assessments/reload.html.erb
  app/views/assessments/show.html.erb
  app/views/assessments/statistics.html.erb
  app/views/assessments/viewFeedback.html.erb
  app/views/assessments/viewGradesheet.html.erb
Labels: large

#1977 lint views/schedulers, views/metrics, views/lti_nrps, views/lti_config, views/extensions
  app/views/extensions/index.html.erb
  app/views/lti_config/index.html.erb
  app/views/lti_nrps/sync_roster.html.erb
  app/views/metrics/index.html.erb
  app/views/schedulers/edit.html.erb
  app/views/schedulers/index.html.erb
  app/views/schedulers/new.html.erb
Labels: medium

#1969 Lint views/submissions
  app/views/submissions/_annotation_form.html.erb
  app/views/submissions/_annotation_pane.html.erb
  app/views/submissions/_annotations_js.html.erb
  app/views/submissions/_code_symbol_tree.html.erb
  app/views/submissions/_code_viewer.html.erb
  app/views/submissions/_file_tree.html.erb
  app/views/submissions/_golden-layout.html.erb
  app/views/submissions/_grades.html.erb
  app/views/submissions/_version_dropdown.html.erb
  app/views/submissions/_version_links.html.erb
  app/views/submissions/annotationsHelp.html.erb
  app/views/submissions/destroyConfirm.html.erb
  app/views/submissions/edit.html.erb
  app/views/submissions/index.html.erb
  app/views/submissions/missing.html.erb
  app/views/submissions/new.html.erb
  app/views/submissions/view.html.erb
  app/views/submissions/view.js.erb
  app/views/submissions/viewPDF.html.erb
Labels: large

#1985 Prevent spoofing the author of an annotation
  app/assets/javascripts/annotations.js
  app/controllers/annotations_controller.rb
Labels: small
