Repository autolab/Autolab, pull requests merged in 2023-03, with the labels that each got.

#1812 Jump to currently enrolled course
  app/controllers/courses_controller.rb
  app/views/layouts/_navbar.html.erb
  config/routes.rb
  spec/features/manage_submissions_spec.rb
Labels: 1 min review

#1826 Add attachment functionality tests
  spec/controllers/attachments_controller_spec.rb
  spec/support/controller_macros.rb
Labels: 20 min review, safe-changes

#1820 Fix bug where course gets created even if there are errors
  app/controllers/courses_controller.rb
  app/views/courses/new.html.erb
Labels: 1 min review

#1833 Fix annotated PDF download when global annotation is present
  app/controllers/submissions_controller.rb
Labels: 1 min review

#1817 Add LTI Configuration to "Manage Autolab" Dropdown, Update docs and gitignore
  .gitignore
  app/views/layouts/_navbar.html.erb
  docs/features/lti-course-integration.md
  docs/images/lti_configuration_settings.png
  docs/images/lti_linked_course_settings.png
  docs/images/lti_manage_course_users.png
  docs/images/lti_sync_roster.png
  docs/installation/lti_integration.md
  docs/installation/osx.md
  docs/installation/ubuntu.md
  mkdocs.yml
Labels: 5 min review

#1825 Create Autolab configure tabs
  .gitignore
  app/assets/javascripts/autolab_config.js
  app/controllers/admins_controller.rb
  app/controllers/lti_config_controller.rb
  app/views/admins/_github_integration.html.erb
  app/views/admins/_lti_integration.erb
  app/views/admins/autolab_config.html.erb
  app/views/layouts/_navbar.html.erb
  config/routes.rb
  spec/controllers/admins_controller_spec.rb
  spec/controllers/lti_config_controller_spec.rb
Labels: 10 min review

#1830 Remove unused "Additional Submission Form" feature code
  app/controllers/assessment/handin.rb
  app/helpers/assessment_autograde_core.rb
  app/models/assessment.rb
  app/models/submission.rb
  app/views/assessments/_edit_basic.html.erb
  app/views/assessments/_handin_form.html.erb
  app/views/submissions/index.html.erb
  app/views/submissions/viewPDF.html.erb
  db/migrate/20230313053555_remove_custom_form_field_from_assessments.rb
  db/schema.rb
Labels: 5 min review

#1838 Fix thead alignment in manage submissions
  app/assets/javascripts/table_floating_header.js
  app/assets/stylesheets/datatable.adapter.css
  app/views/submissions/index.html.erb
Labels: 5 min review

#1839 Autolab config UI smtp
  .gitignore
  app/controllers/admins_controller.rb
  app/controllers/lti_config_controller.rb
  app/controllers/lti_launch_controller.rb
  app/controllers/lti_nrps_controller.rb
  app/controllers/smtp_config_controller.rb
  app/mailers/course_mailer.rb
  app/views/admins/_github_integration.html.erb
  app/views/admins/_smtp_integration.html.erb
  app/views/admins/autolab_config.html.erb
  app/views/course_mailer/test_email.html.erb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb.template
  config/environments/test.rb
  config/routes.rb
  spec/controllers/admins_controller_spec.rb
  spec/controllers/lti_config_controller_spec.rb
  spec/fixtures/config_files/lti_config_template.yml
  spec/fixtures/config_files/lti_platform_jwk_template.json
  spec/fixtures/config_files/lti_tool_jwk_template.json
Labels: 20 min review

#1841 Update MacOS install docs to use Homebrew
  docs/installation/osx.md
  docs/installation/troubleshoot.md
Labels: 1 min review, safe-changes

#1836 Allow GitHub submissions to specify commit SHA
  app/assets/javascripts/git_submission.js
  app/controllers/assessment/handin.rb
  app/controllers/github_integrations_controller.rb
  app/models/github_integration.rb
  app/views/assessments/_submission_panel.html.erb
  config/routes.rb
Labels: 5 min review

#1829 Grade Export: Move total column to be after email
  app/helpers/assessment_helper.rb
  app/views/assessments/_bulkGrade_initial.html.erb
Labels: 1 min review

#1847 Add warning to documentation about RAM requirements
  docs/installation/osx.md
  docs/installation/overview.md
  docs/installation/troubleshoot.md
  docs/installation/ubuntu.md
Labels: 1 min review, safe-changes

#1860 Avoid rounding final score during bulk grade export
  app/helpers/assessment_helper.rb
Labels: 1 min review

#1843 Add GitHub Configuration Tab to Configure Autolab
  .gitignore
  app/controllers/admins_controller.rb
  app/controllers/github_config_controller.rb
  app/views/admins/_github_integration.html.erb
  app/views/admins/_lti_integration.erb
  app/views/admins/_smtp_integration.html.erb
  app/views/admins/autolab_config.html.erb
  config/environments/development.rb
  config/environments/production.rb.template
  config/routes.rb
  docs/installation/github_integration.md
Labels: 5 min review
