Repository autolab/Autolab, pull requests merged in 2023-02, with the labels that each got.

#1753 Change course badge text to correctly reflect course assistant role
  app/views/courses/index.html.erb
Labels: 1 min review

#1749 Add Sorting Icons to Instructor Gradebook
  public/images/sort-asc.gif
  public/images/sort-desc.gif
Labels: 1 min review, safe-changes

#1750 Backend throttling for getPartialFeedback
  config/initializers/rack-attack.rb
Labels: 1 min review

#1779 Make blue darker to help with contrast
  app/assets/stylesheets/_variables.scss
Labels: 1 min review

#1780 Wrap long lines in annotations
  app/assets/stylesheets/annotations.scss
  app/views/submissions/_annotation_pane.html.erb
Labels: 1 min review

#1740 Redirect instructor to manage submissions page after updating submission
  app/controllers/submissions_controller.rb
Labels: 1 min review

#1747 Filter error handler scores before rendering view statistics page
  app/controllers/assessment/grading.rb
Labels: 1 min review

#1785 Link to submission page for ungraded assignments
  app/views/gradebooks/student.html.erb
Labels: 1 min review

#1805 Update workflows to work with merge queue
  .github/workflows/codeql-analysis.yml
  .github/workflows/rubyonrails.yml
Labels: 5 min review

#1778 fixed word breaks in course cards
  app/assets/stylesheets/style.css.scss
Labels: 1 min review

#1789 Improve delete user functionality
  app/controllers/users_controller.rb
  app/views/users/edit.html.erb
  app/views/users/show.html.erb
Labels: 1 min review

#1758 Changed "Manage Autolab" button from a page redirect to a dropdown
  Gemfile
  app/assets/stylesheets/navbar.css
  app/controllers/admins_controller.rb
  app/views/admins/show.html.erb
  app/views/assessments/index.html.erb
  app/views/layouts/_navbar.html.erb
  config/routes.rb
  spec/controllers/admins_controller_spec.rb
Labels: 1 min review

#1807 Annotation scrolling to line UI bug fix
  app/assets/javascripts/annotations.js
Labels: 1 min review

#1804 Create tests for add_users_from_emails, unlink_course, update_lti_settings, download_roster for CoursesController
  app/controllers/courses_controller.rb
  spec/controllers/courses_controller_spec.rb
  spec/factories/course_user_datum.rb
  spec/factories/courses.rb
  spec/factories/lti_course_datum.rb
  spec/factories/users.rb
  spec/support/controller_macros.rb
Labels: 20 min review

#1773 Configuration for URL generation
  .env.template
  app/views/assessments/index.html.erb
  config/application.rb
  docs/installation/mailing.md
Labels: 1 min review

#1760 Autofill scores for shared comments
  app/assets/javascripts/annotations.js
  app/controllers/annotations_controller.rb
Labels: 5 min review

#1809 Add loading spinner to annotations panel when annotations are updating
  app/assets/javascripts/annotations.js
  app/assets/stylesheets/annotations.scss
  app/views/submissions/_annotation_pane.html.erb
Labels: 1 min review

#1801 Button to clear cache (in dropdown)
  app/controllers/admins_controller.rb
  app/views/layouts/_navbar.html.erb
  config/routes.rb
  docs/installation/troubleshoot.md
Labels: 1 min review

#1816 Create Sample Course Factory
  spec/controllers/courses_controller_spec.rb
  spec/factories/problems.rb
  spec/factories/submissions.rb
  spec/support/controller_macros.rb
Labels: 5 min review, safe-changes

#1784 Gradebook sorting icon & styling
  app/assets/javascripts/SlickGrid/2.02/slick.grid.js
  app/assets/stylesheets/SlickGrid/2.02/slick.grid.css
  app/assets/stylesheets/gradesheet.css.scss
  app/assets/stylesheets/instructor_gradebook.scss
  app/views/gradebooks/view.html.erb
Labels: 1 min review

#1818 Enable Rubocop Linting within /spec directory
  .rubocop.yml
  spec/api/v1/api_shared_context.rb
  spec/api/v1/assessments_api_spec.rb
  spec/api/v1/course_user_data_api_spec.rb
  spec/api/v1/courses_api_spec.rb
  spec/api/v1/device_flow_requests_spec.rb
  spec/api/v1/problems_api_spec.rb
  spec/api/v1/submission_roundtrip_spec.rb
  spec/api/v1/tango_mock.rb
  spec/api/v1/user_api_spec.rb
  spec/controllers/attachments_controller_spec.rb
  spec/controllers/home_controller_spec.rb
  spec/controllers/lti_config_controller_spec.rb
  spec/controllers/schedulers_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/features/manage_submissions_spec.rb
  spec/models/annotation_spec.rb
  spec/rails_helper.rb
  spec/support/controller_macros.rb
Labels: 30 min review

#1821 Fix bug in GitHub api rate limit check
  app/models/github_integration.rb
Labels: 1 min review

#1823 Update docker compose docs
  docs/installation/docker-compose.md
Labels: 1 min review, safe-changes

#1822 Update Export / Import Assessment to support more fields, make importAsmtFromTar and importAssessment more robust
  app/controllers/assessments_controller.rb
  app/models/assessment.rb
  spec/controllers/assessments_controller_spec.rb
  spec/factories/assessments.rb
  spec/fixtures/assessments/homework02-correct.tar
  spec/fixtures/assessments/homework02-file-mismatch.tar
  spec/fixtures/assessments/homework02-illegal-assessment-name.tar
  spec/fixtures/assessments/homework02-module-mismatch.tar
  spec/fixtures/assessments/homework02-yaml-name-field-wrong.tar
  spec/fixtures/assessments/homework02_badsyntax.tar
  spec/support/controller_macros.rb
Labels: 20 min review

#1810 [Breaking] Use ActiveStorage for attachments, update attachments tests
  .github/workflows/codeql-analysis.yml
  .github/workflows/rubyonrails.yml
  .gitignore
  README.md
  app/controllers/attachments_controller.rb
  app/models/attachment.rb
  app/views/attachments/_attachment.html.erb
  config/environments/development.rb
  config/environments/production.rb.template
  config/environments/test.rb
  db/migrate/20230212191438_create_active_storage_tables.active_storage.rb
  db/schema.rb
  spec/controllers/attachments_controller_spec.rb
  spec/factories/attachments.rb
  spec/fixtures/attachments/assessment.txt
  spec/fixtures/attachments/attachment.txt
  spec/fixtures/attachments/course.txt
  spec/support/controller_macros.rb
Labels: 30 min review
