Repository autolab/Autolab, pull requests merged in 2023-05, with the labels that each got.

#1898 Fix 500 error from going to users/id for non-existent user-id
  app/controllers/users_controller.rb
Labels: 1 min review

#1892 OAuth flow fix
  app/assets/stylesheets/style.css.scss
  app/controllers/users/omniauth_callbacks_controller.rb
  app/models/user.rb
  app/views/devise/sessions/new.html.erb
  config/initializers/devise.rb
Labels: 5 min review

#1900 Handin improvements
  app/assets/javascripts/git_submission.js
  app/assets/javascripts/handin.js
  app/controllers/assessment/handin.rb
  app/views/assessments/_handin_form.html.erb
Labels: 1 min review

#1893 Adds Score Details
  app/assets/javascripts/manage_submissions.js
  app/assets/stylesheets/manage_submissions.css
  app/controllers/submissions_controller.rb
  app/views/submissions/index.html.erb
  config/routes.rb
Labels: 20 min review

#1902 Autolab v3.0.0
  config/application.rb
Labels: 1 min review

#1878 Extension metrics
  app/assets/javascripts/metrics.js
  app/assets/javascripts/watchlist.js
  app/controllers/metrics_controller.rb
  app/models/risk_condition.rb
  app/models/watchlist_instance.rb
  app/views/metrics/index.html.erb
Labels: 5 min review

#1906 Fix directory permissions for assessment imports
  app/controllers/assessments_controller.rb
  lib/archive.rb
Labels: 1 min review

#1894 Setup erb-lint, lint views/admins files
  .erb-lint.yml
  Gemfile
  Gemfile.lock
  app/views/admins/email_instructors.html.erb
  app/views/admins/github_integration.html.erb
Labels: 5 min review

#1901 Correctly display PDF annotations on viewFeedback page
  app/views/assessments/_remarks_panel.html.erb
Labels: 1 min review

#1905 Fix styling of create course form
  app/assets/stylesheets/style.css.scss
  app/views/courses/new.html.erb
Labels: 1 min review

#1899 Autolab v2.11.0
  .cm/gitstream.cm
  README.md
  config/application.rb
Labels: cm-changes
