Repository autolab/Autolab, pull requests merged in 2023-11, with the labels that each got.

#1990 Display Grace Day usage on submission history table, improve management of assessment penalty settings
  app/assets/javascripts/edit_assessment.js
  app/assets/stylesheets/style.css.scss
  app/controllers/assessments_controller.rb
  app/form_builders/form_builder_with_date_time_input.rb
  app/models/score_adjustment.rb
  app/views/assessments/_edit_penalties.html.erb
  app/views/assessments/_submission_history_row.html.erb
  app/views/assessments/_submission_history_table.html.erb
  app/views/assessments/edit.html.erb
  app/views/courses/_courseFields.html.erb
  config/initializers/core_ext.rb
Labels: medium

#1982 Handle malformed scoreboard results from autograder, fix error handling for scoreboards
  app/assets/stylesheets/style.css.scss
  app/controllers/scoreboards_controller.rb
  app/views/scoreboards/_error_icon.html.erb
  app/views/scoreboards/_form.html.erb
  app/views/scoreboards/show.html.erb
Labels: small

#1998 Click into submissions from gradebook score
  app/assets/javascripts/gradebook.js
  app/helpers/gradebook_helper.rb
Labels: small

#1997 Switch mossnet clean to use rails root instead of tilde expansion
  app/controllers/courses_controller.rb
Labels: small

#2001 Check that handout/writeup exists before checking path
  app/models/assessment.rb
Labels: small

#1999 Adds warning when assessment.rb file upload isn't a .rb file
  Gemfile.lock
  app/assets/javascripts/edit_assessment.js
  app/views/assessments/_edit_basic.html.erb
Labels: small

#1987 Refactor Assessment name rules, remove config file requirement
  app/controllers/assessment/autograde.rb
  app/controllers/assessments_controller.rb
  app/helpers/assessment_autograde_core.rb
  app/models/assessment.rb
  app/models/oauth_device_flow_request.rb
  app/models/user.rb
  app/views/assessments/_edit_basic.html.erb
  docs/lab.md
  spec/controllers/assessments_controller_spec.rb
  spec/fixtures/assessments/homework02-illegal-assessment-name.tar
  spec/fixtures/assessments/homework02-legal-name-no-config.tar
Labels: large

#2004 Suppress confirmation dialog on edit assessment page when no changes made
  app/assets/javascripts/edit_assessment.js
  app/models/assessment.rb
Labels: small

#2005 Display submission version in gradebook
  app/assets/javascripts/gradebook.js
  app/assets/stylesheets/instructor_gradebook.scss
  app/helpers/gradebook_helper.rb
  app/models/grade_matrix.rb
  app/models/user.rb
Labels: small, waiting-for-review

#2006 Don't clear assessment penalty fields on initial load
  app/assets/javascripts/edit_assessment.js
Labels: small, waiting-for-review

#2008 No line breaks when generating base64 strings
  app/assets/javascripts/base64.js
Labels: medium, waiting-for-review

#2015 Show all courses for MOSS
  app/assets/javascripts/dropdown.js
  app/assets/javascripts/moss.js
  app/assets/stylesheets/style.css.scss
  app/controllers/courses_controller.rb
  app/views/components/_dropdown_icon.html.erb
  app/views/courses/moss.html.erb
  spec/features/manage_submissions_spec.rb
Labels: large

#1993 Removed name from assessment yml
  app/controllers/assessments_controller.rb
  app/models/assessment.rb
  spec/controllers/assessments_controller_spec.rb
Labels: small
