Repository autolab/Autolab, pull requests merged in 2023-12, with the labels that each got.

#2003 Account for hooks in viewFeedback instead of feedback output
  app/controllers/assessments_controller.rb
Labels: small

#2009 Remove element overlapping scrollbar hitbox
  app/assets/stylesheets/annotations.scss
Labels: small

#1983 Attachment categories
  app/assets/stylesheets/style.css.scss
  app/controllers/assessments_controller.rb
  app/controllers/attachments_controller.rb
  app/models/attachment.rb
  app/views/assessments/index.html.erb
  app/views/assessments/show.html.erb
  app/views/attachments/_attachment.html.erb
  app/views/attachments/_course_attachment.html.erb
  app/views/attachments/_form.html.erb
  db/migrate/20230912193510_add_category_name_to_attachments.rb
  db/migrate/20230924161219_add_release_at_to_attachments.rb
  db/migrate/20230924163059_remove_released_from_attachments.rb
  db/schema.rb
  spec/controllers/attachments_controller_spec.rb
  spec/factories/attachments.rb
  spec/fixtures/attachments/assessment.txt
  spec/fixtures/attachments/attachment.txt
  spec/fixtures/attachments/course.txt
  spec/support/controller_macros.rb
Labels: large

#1984 Passwordless temporary login
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/users/show.html.erb
  app/views/users/update_password_for_user.html.erb
  config/routes.rb
  docs/features/admin-features.md
  docs/instructors.md
  mkdocs.yml
Labels: small

#2016 Visual cue for assessments
  app/assets/stylesheets/assessments.scss
  app/models/assessment.rb
  app/views/assessments/index.html.erb
Labels: small

#2023 Use ActiveStorage for attachments, add attachment size limit
  .github/workflows/rubyonrails.yml
  .gitignore
  README.md
  app/controllers/attachments_controller.rb
  app/models/attachment.rb
  app/views/attachments/_form.html.erb
  config/environments/development.rb
  config/environments/production.rb.template
  config/environments/test.rb
  db/migrate/20231208034215_create_active_storage_tables.active_storage.rb
  db/schema.rb
Labels: medium
