Repository autolab/Autolab, pull requests merged in 2024-02, with the labels that each got.

#2012 Export course
  app/assets/javascripts/export_course.js
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/export.scss
  app/controllers/courses_controller.rb
  app/models/attachment.rb
  app/models/course.rb
  app/models/risk_condition.rb
  app/models/watchlist_configuration.rb
  app/views/courses/_exportForm.html.erb
  app/views/courses/export.html.erb
  app/views/courses/manage.html.erb
  config/routes.rb
  spec/contexts_helper.rb
  spec/controllers/courses_controller_spec.rb
  spec/factories/attachments.rb
  spec/factories/courses.rb
  spec/fixtures/attachments/hyperfastparrot.gif
  spec/sets/courses.rb
Labels: large, waiting-for-review

#2066 Fix Yaml file in assessment not being updated properly after import, ensure proper loading of version penalty and late penalty
  app/models/assessment.rb
  spec/controllers/assessments_controller_spec.rb
  spec/fixtures/assessments/all-fields-filled.tar
  spec/rails_helper.rb
Labels: small, waiting-for-review

#2072 Replace reviewpad with gitstream
  .cm/gitstream.cm
  .github/pull_request_template.md
  .github/workflows/gitstream.yml
  reviewpad.yml
Labels: cm-changes

#2073 Gitstream: fix evaluation of colors
  .cm/gitstream.cm
Labels: cm-changes

#2074 Update gitstream.cm
  .cm/gitstream.cm
Labels: cm-changes

#2075 Create dependabot.yml to automatically update github actions
  .github/dependabot.yml
Labels: small

#2013 Add docker image uploading
  app/controllers/dockers_controller.rb
  app/helpers/assessment_autograde_core.rb
  app/views/autograders/_form.html.erb
  app/views/courses/manage.html.erb
  app/views/dockers/index.html.erb
  config/environments/development.rb
  config/environments/production.rb.template
  config/environments/test.rb
  config/routes.rb
  lib/tango_client.rb
Labels: small

#2084 Allow instructors to also be CAs
  app/assets/javascripts/course_user_data_edit.js
  app/models/course_user_datum.rb
Labels: small

#2071 Use instance variables instead of flash to display duplicates during roster import
  app/controllers/courses_controller.rb
  app/views/courses/_uploadError.html.erb
  app/views/courses/upload_roster.html.erb
  app/views/layouts/application.html.erb
Labels: small

#2082 Remove custom pluralize method in application_controller.rb
  app/controllers/application_controller.rb
  app/controllers/assessment/autograde.rb
Labels: small

#2083 Add tests for extensions
  app/controllers/extensions_controller.rb
  spec/controllers/extensions_controller_spec.rb
Labels: medium

#2097 Add fixes for extension tests
  spec/controllers/extensions_controller_spec.rb
Labels: small

#2098 Fix flaky capybara test
  spec/features/assessment_spec.rb
Labels: small

#2100 Fix page title for app authorization
  app/views/doorkeeper/authorizations/new.html.erb
Labels: small

#2091 Export files inside nested directories
  app/controllers/assessments_controller.rb
  app/models/assessment.rb
  app/models/course.rb
Labels: small, waiting-for-review

#2099 Include the max total score in the submissions table header
  app/views/assessments/_submission_history_table.html.erb
Labels: small, waiting-for-review

#2092 Fix scoreboard sorting failing on custom scoreboardOrderSubmissions, add more error checking when creating scoreboard entries / displaying
  app/controllers/scoreboards_controller.rb
  app/views/scoreboards/_form.html.erb
  app/views/scoreboards/show.html.erb
  config/routes.rb
Labels: medium, waiting-for-review

#2101 Allow instructors to be included on scoreboards
  app/controllers/scoreboards_controller.rb
  app/views/scoreboards/_form.html.erb
  app/views/scoreboards/show.html.erb
  db/migrate/20240208143255_add_include_instructors_to_scoreboard.rb
  db/schema.rb
Labels: small, waiting-for-review

#2011 Import course and refactor assessment import
  app/assets/javascripts/app-level.js
  app/assets/javascripts/edit_assessment.js
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/install_assessment.css.scss
  app/controllers/assessments_controller.rb
  app/controllers/courses_controller.rb
  app/models/assessment.rb
  app/views/assessments/_install_assessment_table.html.erb
  app/views/assessments/_install_assessment_table_js.html.erb
  app/views/assessments/course_onboard_install_asmt.html.erb
  app/views/assessments/install_assessment.html.erb
  app/views/courses/_create_new_course.html.erb
  app/views/courses/_import_new_course.html.erb
  app/views/courses/edit.html.erb
  app/views/courses/new.html.erb
  config/routes.rb
  spec/controllers/assessments_controller_spec.rb
  spec/controllers/courses_controller_spec.rb
  spec/fixtures/courses/course-bad-config-syntax.tar
  spec/fixtures/courses/course-invalid.tar
  spec/fixtures/courses/course-mismatch-yml.tar
  spec/fixtures/courses/course-missing-yml.tar
  spec/fixtures/courses/course-no-root.tar
  spec/fixtures/courses/course-valid.tar
Labels: large, waiting-for-review

#2081 Added a button to release/unrelease grades
  app/assets/javascripts/annotations.js
  app/controllers/submissions_controller.rb
  app/helpers/submission_helper.rb
  app/models/submission.rb
  app/views/assessments/_handin_form.html.erb
  app/views/submissions/_grades.html.erb
  app/views/submissions/_release_grades.html.erb
  app/views/submissions/view.html.erb
  config/routes.rb
Labels: small

#2093 Code Diff Viewer, version switching on Autograder Output
  Gemfile
  Gemfile.lock
  app/assets/javascripts/annotations.js
  app/assets/javascripts/app-level.js
  app/assets/javascripts/diff_viewer.js
  app/assets/javascripts/submission_view.js
  app/assets/stylesheets/annotations.scss
  app/controllers/submissions_controller.rb
  app/helpers/application_helper.rb
  app/views/announcements/_announcements_list.html.erb
  app/views/assessments/_downloadSubmission.html.erb
  app/views/assessments/index.html.erb
  app/views/submissions/_annotations_js.html.erb
  app/views/submissions/_code_viewer.html.erb
  app/views/submissions/_diff_viewer.html.erb
  app/views/submissions/_golden-layout.html.erb
  app/views/submissions/view.html.erb
  app/views/submissions/view.js.erb
Labels: large, waiting-for-review
