Repository autolab/Autolab, pull requests merged in 2024-01, with the labels that each got.

#2037 Rails 6.1.7.6 Migration
  .github/workflows/rubyonrails.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/assessments_controller.rb
  app/controllers/assessment/grading.rb
  app/controllers/assessment/handin.rb
  app/controllers/assessment/handout.rb
  app/controllers/assessments_controller.rb
  app/controllers/courses_controller.rb
  app/controllers/groups_controller.rb
  app/controllers/submissions_controller.rb
  app/helpers/assessment_handin_core.rb
  app/models/assessment.rb
  app/models/assessment_user_datum.rb
  app/models/course.rb
  app/models/score.rb
  app/models/submission.rb
  app/views/assessments/show.html.erb
  app/views/assessments/statistics.html.erb
  app/views/assessments/viewGradesheet.html.erb
  app/views/gradebooks/view.html.erb
  app/views/layouts/application.html.erb
  bin/rails
  bin/rake
  bin/setup
  bin/spring
  config.ru
  config/application.rb
  config/boot.rb
  config/environment.rb
  config/environments/development.rb
  config/environments/test.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/new_framework_defaults_6_1.rb
  config/initializers/permissions_policy.rb
  config/routes.rb
  db/migrate/20240101084756_add_service_name_to_active_storage_blobs.active_storage.rb
  db/migrate/20240101084757_create_active_storage_variant_records.active_storage.rb
  db/schema.rb
  spec/controllers/courses_controller_spec.rb
Labels: large

#2044 Update old migrations for Ruby 3
  db/migrate/007_add_instructor_to_users.rb
  db/migrate/20100723040512_add_gradebook_caching.rb
  db/migrate/20100807150918_remove_key_from_gradebook_cache.rb
  db/migrate/20100826234109_make_andrew_id_unique_key.rb
  db/migrate/20101220043448_add_disabled_to_courses.rb
  db/migrate/20120204025713_add_tweak_type_to_submissions.rb
  db/migrate/20120204061221_add_tweak_type_to_users.rb
  db/migrate/20130121040729_remove_unused_gradebook_caching.rb
Labels: small

#2014 Remove grading deadline
  app/assets/javascripts/gradebook.js
  app/assets/javascripts/init_handin_datetimepickers.js
  app/controllers/api/v1/assessments_controller.rb
  app/controllers/assessments_controller.rb
  app/controllers/submissions_controller.rb
  app/helpers/gradebook_helper.rb
  app/models/assessment.rb
  app/models/assessment_user_datum.rb
  app/models/grade_matrix.rb
  app/models/submission.rb
  app/models/watchlist_instance.rb
  app/views/assessments/_edit_handin.html.erb
  app/views/assessments/_remarks_panel.html.erb
  app/views/assessments/_results_panel.html.erb
  app/views/gradebooks/student.html.erb
  app/views/submissions/_annotation.html.erb
  app/views/submissions/_annotation_pane.html.erb
  db/migrate/20231201202449_remove_grading_deadline_from_assessments.rb
  db/schema.rb
  docs/api-interface.md
  docs/instructors.md
  lib/tasks/autolab.rake
  spec/controllers/assessments_controller_spec.rb
  spec/factories/assessments.rb
Labels: medium

#2038 Address issues from v2.8.0 testing, misc fixes/changes
  .gitignore
  app/assets/javascripts/collapsible.js
  app/controllers/application_controller.rb
  app/controllers/submissions_controller.rb
  app/helpers/assessment_autograde_core.rb
  app/models/submission.rb
  app/views/assessments/index.html.erb
  app/views/assessments/show.html.erb
  app/views/courses/manage.html.erb
  app/views/home/no_user.html.erb
  config/locales/doorkeeper.en.yml
  docs/features/embedded-forms.md
  docs/tango-rest.md
Labels: large

#1956 Update the API to allow retrieving group members
  app/controllers/api/v1/groups_controller.rb
  app/models/assessment.rb
  config/initializers/core_ext.rb
  config/routes.rb
  docs/api-interface.md
Labels: small

#2045 Update index and show docs for Groups API
  docs/api-interface.md
Labels: small

#2050 Remove gradebooks directory
  .gitignore
  app/models/course.rb
Labels: small

#2049 Load enable_starttls_auto as a boolean
  app/controllers/application_controller.rb
  app/controllers/courses_controller.rb
  config/environments/production.rb.template
Labels: small

#2056 Autolab v2.12.0
  README.md
  config/application.rb
Labels: small

#2058 Remove redundant conditional to migrate config file, Allow empty config file to be loaded
  app/controllers/assessment/handout.rb
  app/controllers/assessments_controller.rb
  app/models/assessment.rb
Labels: small

#2064 Update installation instructions for Ubuntu 22.04
  docs/installation/overview.md
  docs/installation/tango.md
  docs/installation/ubuntu.md
  mkdocs.yml
Labels: medium

#2018 Overwrite labs on reupload
  app/controllers/assessments_controller.rb
  app/models/assessment.rb
  app/models/course_logger.rb
  app/views/assessments/install_assessment.html.erb
  spec/controllers/assessments_controller_spec.rb
Labels: small
